# Zachary Jewel Schmitz
# Chris Caldwell
# CPSC 1071: Section 001
# 22 November 2021

compile:
	gcc -c Project-4.c
	gcc Project-4.o -o driver.out

clean:
	rm *.o *.out *.jpg

run:
	./driver.out deleted_pat_pictures.raw

reset:
	make clean
	make 
	make run
