compile:
	g++ -c Dealer.cpp Card.cpp AnalyzeHand.cpp BlackjackRules.cpp PokerRules.cpp
	g++ -o deal.out -Wall Dealer.o Card.o AnalyzeHand.o BlackjackRules.o PokerRules.o
run:
	./deal.out
clean:
	rm *.o
